[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "orchestration"
version = "0.1.0"
dependencies = ["dagster", "dagster-webserver", "batch-data-pipeline"]

[tool.setuptools]
packages = ["orchestration"]
